# Generated by Django 5.1.7 on 2025-07-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userbase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128)),
                ('public', models.BooleanField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='asset/user_profile')),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
