# Generated by Django 5.1.7 on 2025-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='email',
            field=models.EmailField(default='a@bcd.com', max_length=254),
            preserve_default=False,
        ),
    ]
