# Generated by Django 5.1.7 on 2025-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0002_userbase_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
