# Generated by Django 5.1.7 on 2025-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbase', '0004_rename_profile_userbase_profileimg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userbase',
            name='skills',
            field=models.ManyToManyField(blank=True, to='userbase.skill'),
        ),
    ]
